name: moveapps-python-sdk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  - pandas
  - geopandas
  - movingpandas
  - rasterio
  - rioxarray
  - pyproj
  - shapely
  - gdal

  - qt-main
  - pyqt6
  - compilers
  - cmake
  - pluggy
  - python-dotenv
  - deprecated

  # only for release
  - pip:
    - "git+https://github.com/ls11ae/random-walks-python.git@47073df1eb1f33c3ce6b4da9fe8696c59dfaea8a#submodules=true"
