name: moveapps-python-sdk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - geopandas
  - movingpandas
  - pluggy
  - python-dotenv
  - deprecated

  # only for release
  - pip:
       - "git+https://github.com/ls11ae/random-walks-python.git@state-walks#submodules=true"